---
- name: demo on variables
  hosts: localhost
  become: true
  vars:
    course: devops
    duration: 4 months
    fee: 3000
    
  tasks:
   - debug:
      msg: hi  iam learnig {{course}}, period of {{duration}}, 4 months. 