- name: demo on vars_files
  hosts: localhost
  connection: local
  vars_files:
    - course.yaml                    
  tasks:
    - name: print variables information
      ansible.builtin.debug:
        msg: "Hi, I am learning {{ COURSE }}. The trainer is {{ TRAINER }} and the duration is {{ DURATION }}."