- name: check no of live sessions
  hosts: localhost
  connection: local
  vars:
    LIVE_SESSIONS: 6
  tasks:
    - name: is ansible more than 5 sessions
      ansible.builtin.debug:
        msg: "yes, ansible took more than 5 sessions"
      when: LIVE_SESSIONS > 5




      ## out put is  "yes " ansible took more then 5 session