---
- name: even or odd
  hosts: localhost
  connection: local
  vars:
    given_number: 7
  tasks:
    - name: check if even
      ansible.builtin.debug:
        msg: "Given number {{ given_number }} is even"
      when: given_number % 2 == 0

    - name: check if odd
      ansible.builtin.debug:
        msg: "Given number {{ given_number }} is odd"
      when: given_number % 2 != 0

