---
- name: install packages
  hosts: localhost
  connection: local
  become: true
  tasks:
    - name: install packages using loop
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop:
        - nginx
        - mysql
        - git