---
- name: demo on filter
  hosts: localhost
  connection: local
  vars:
    topics: "linux, ansible, shell, terraform"
  tasks:
    - name: convert to list
      ansible.builtin.debug:
        msg: "{{ topics | split(',') }}"