

[local]        ansible_connection=local
 localhost
 
local: vars
COURSE: ansible
TRAINER: vinay
DURATION: 150 hours


 ##172.31.21.237


[mysql]
172.31.21.232

[mongodb]
172.31.21.239

[cart]
172.31.21.230
